// <auto-generated />
using System;
using Corvette.MeteoExport.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Corvette.MeteoExport.Core.Migrations
{
    [DbContext(typeof(MeteoExportDbContext))]
    partial class MeteoExportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Corvette.MeteoExport.Core.Entities.ExportJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunksDone")
                        .HasColumnType("integer")
                        .HasColumnName("chunks_done");

                    b.Property<int>("ChunksTotal")
                        .HasColumnType("integer")
                        .HasColumnName("chunks_total");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResultFilePath")
                        .HasColumnType("text")
                        .HasColumnName("result_file_path");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.PrimitiveCollection<string[]>("Variables")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("variables");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_export_jobs");

                    b.HasIndex("RequestHash")
                        .IsUnique()
                        .HasDatabaseName("uix_export_jobs_request_hash_active")
                        .HasFilter("status in (1, 2)");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_export_jobs_status_created_at");

                    b.ToTable("export_jobs");
                });

            modelBuilder.Entity("Corvette.MeteoExport.Core.Entities.ExportJobEntity", b =>
                {
                    b.OwnsMany("Corvette.MeteoExport.Core.Models.ExportPoint", "Points", b1 =>
                        {
                            b1.Property<Guid>("ExportJobEntityId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double>("Latitude")
                                .HasJsonPropertyName("latitude");

                            b1.Property<double>("Longitude")
                                .HasJsonPropertyName("longitude");

                            b1.Property<string>("Name")
                                .HasJsonPropertyName("name");

                            b1.HasKey("ExportJobEntityId", "__synthesizedOrdinal");

                            b1.ToTable("export_jobs");

                            b1
                                .ToJson("points")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ExportJobEntityId");
                        });

                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
